
tokenizer_file: ./tokenizers/tokenizer_{0}.json
yml_config_file_name: config.yml
#config_dir: ./
dataset_name: opus_books
Subset: en-fr
src_lang: en
tgt_lang: fr
batch_size: 8
effective_batch: 64
num_epochs: 30
model:
#    On_DS_name: OriginalTexts
    On_DS_name: OpusBText
    d_model: 16
#    d_f: 2048
    d_f: 32
    dropout: 0.1
    N_enc: 6
    N_dec: 6
    heads: 4
    lr: 1e-4
    checkpoint_dir_name: checkpoints
    model_basename: transformer
#    last_epoch: false    # store epoch num
#    model_dir: false

experiment:
    name: experiments/TransOpusBook

